services:
  backend:
    env_file:
      - .env
    build:
      context: ../..
      dockerfile: .Dockerfile
    ports:
      - "8080:8080"
    container_name: spring-photi
    environment:
      - TZ=Asia/Seoul
    networks:
      - server-network

networks:
  server-network:
    external: true
    driver: bridge