services:
  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
      - LOGGING_FILE_PATH=/logs
    networks:
      - server-network
    volumes:
      - /home/ubuntu/logs:/logs
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /var/lib/docker/volumes/redis/data:/data
    restart: always
    networks:
      - server-network

networks:
  server-network:
    external: true
    driver: bridge