services:
  enduser:
    container_name: enduser-server
    restart: always
    build:
      context: .
      dockerfile: photi-apis/enduser/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - docker/.env
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - db
      - redis
      - redis-init
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres!2#
      POSTGRES_DB: photi_local_db
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-db
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  redis-init:
    image: redis:latest
    container_name: redis-init
    restart: "no"
    depends_on:
      - redis
    entrypoint: [ "bash", "-c", "/init/redis-init.sh" ]
    volumes:
      - ./docker/redis-init.sh:/init/redis-init.sh:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
