version: '3.9'

services:
  alloon:
    restart: always
    env_file:
      - docker/.env
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mem-db
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres!2#
      POSTGRES_DB: allon_server
  mem-db:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis-init.sh:/redis-init.sh
    command: [ "sh", "-c", "redis-server --daemonize yes && sleep 3 && bash /redis-init.sh && tail -f /dev/null" ]
