spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://0.0.0.0:5432/postgres
    username: postgres
    password: 1234

  sql:
    init:
      mode: always

logging:
  config: classpath:logback/dev-logback.xml

sentry:
  dsn:

api:
  name: "Alloon Local"