spring:
  profiles:
    default: local

###################
###### LOCAL ######
###################
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alloon_local?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: false
        format_sql: true
        use_sql_comments: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            require: true

api:
  name: "Alloon Local"
  master:
    id: alloon
  jwt:
    secret: ${JWT_SECRET}
    domain: ${JWT_DOMAIN}
    time:
      access: ${JWT_ACCESS}
      refresh: ${JWT_REFRESH}
  mail:
    address: ${MAIN_ADDRESS}

###################
###### TEST #######
###################
---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alloon_local?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: false
        format_sql: true
        use_sql_comments: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            require: true

api:
  name: "Alloon Test"
  master:
    id: alloon
  jwt:
    secret: ${JWT_SECRET}
    domain: ${JWT_DOMAIN}
    time:
      access: ${JWT_ACCESS}
      refresh: ${JWT_REFRESH}
  mail:
    address: ${MAIN_ADDRESS}

###################
####### DEV #######
###################
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: ${SQL_INIT_MODE}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: false
        format_sql: true
        use_sql_comments: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            require: true

api:
  name: "Alloon Dev"
  master:
    id: alloon
  jwt:
    secret: ${JWT_SECRET}
    domain: ${JWT_DOMAIN}
    time:
      access: ${JWT_ACCESS}
      refresh: ${JWT_REFRESH}
  mail:
    address: ${MAIN_ADDRESS}