services:
  backend:
    image: yugyeong390/photi-server:1.1.4
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/logs:/logs
    environment:
      - TZ=Asia/Seoul
      - LOGGING_FILE_PATH=/logs
    networks:
      - server-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - server-network

volumes:
  redis-data:
    driver: local

networks:
  server-network:
    external: true
    driver: bridge