spring:
  profiles:
    active: local
    include:
      - domain
  config:
    import: optional:file:.env[.properties]
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  servlet:
    multipart:
      max-request-size: 8MB
      max-file-size: 8MB
---
spring:
  config:
    activate:
      on-profile: local
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      access-exp: ${JWT_ACCESS}
      refresh-exp: ${JWT_REFRESH}

springdoc: # TODO 수정 필요
  swagger-ui:
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
---
spring:
  config:
    activate:
      on-profile: dev
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      access-exp: ${JWT_ACCESS}
      refresh-exp: ${JWT_REFRESH}

springdoc: # TODO 수정 필요
  swagger-ui:
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
---
spring:
  config:
    activate:
      on-profile: prod
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      access-exp: ${JWT_ACCESS}
      refresh-exp: ${JWT_REFRESH}

springdoc:
  swagger-ui:
    enabled: false

management: # TODO 수정 필요
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true
