name: discussion notification

on:
  discussion:
    types: [ created ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Escape discussion body using jq
        id: prepare
        run: |
          BODY="${{ github.event.discussion.body }}"
          ESCAPED_BODY=$(echo "$BODY" | tr -d '\r' | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/`/\&#96;/g')
          CLEAN_BODY=$(jq -Rsa . <<< "$ESCAPED_BODY" | sed 's/^"//' | sed 's/"$//')
          echo "body=$CLEAN_BODY" >> $GITHUB_OUTPUT

      - name: Send Discord notification
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 디스커션 봇
          DISCORD_AVATAR: https://avatars.githubusercontent.com/u/154582156?s=400&u=de1c7ebc9093ce26761a93a1cd78429bc4abe889&v=4
          DISCORD_EMBEDS: >-
            [{"title":"${{ github.event.discussion.title }}","color":6253567,"url":"${{ github.event.discussion.html_url }}","description":"${{ steps.prepare.outputs.body }}"}]
